app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # file listing page
    path('', views.FileListView.as_view(), name='file_list'),
    # using models
    path('single/upload/model/', views.SingleUploadWithModelView.as_view(), name='single_upload_with_model'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# if you want to list/edit/delete uploaded files, then you want to use models

from django.db import models


class UploadFile(models.Model):
    """ models for uploaded file """
    file = models.ImageField('image file')

    def __str__(self):
        """ return file url """
        return self.file.url

app/forms.py
from django import forms
from .models import UploadFile


class SingleUploadModelForm(forms.ModelForm):

    class Meta:
        model = UploadFile
        fields = '__all__'

app/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import SingleUploadModelForm
from .models import UploadFile


class SingleUploadWithModelView(generic.CreateView):
    """ view to upload file model """
    model = UploadFile
    form_class = SingleUploadModelForm
    template_name = 'app/upload.html'
    success_url = reverse_lazy('app:file_list')

class FileListView(generic.ListView):
    """ view for page listing all uploaded files """
    model = UploadFile

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>File Upload</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

app/templates/app/upload.html
<form action="" method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Submit</button>
</form>

    {% if download_url %}
        <a href="{{ download_url }}">{{ download_url }}</a>
    {% endif %}

app/templates/app/uploadfile_list.html
{% extends 'app/base.html' %}

{% block content %}
    <p><a href="{% url 'app:single_upload_with_model' %}">Go to File Upload Page</a></p>
    <h1>List of files</h1>
    {% for uploadfile in uploadfile_list %}
        <p><a href="{{ uploadfile.file.url }}">{{ uploadfile.file.url }}</a></p>
    {% endfor %}
{% endblock %}